"""
Django settings for recruitment_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-28m+31iz9m0-x0ylw7)*dh-zerl9k$lqhfj1er@l(o^zflw*!1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'job',
    'home',
    'banner',
    'introduce',
    'django_ckeditor_5',
    'gallery',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recruitment_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "home/templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recruitment_project.wsgi.application'
CKEDITOR_5_CONFIGS = {
    "extends": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strike", "|",
            "fontColor", "fontBackgroundColor", "|",
            "bulletedList", "numberedList", "alignment", "|",
            "link", "insertTable", "imageUpload", "mediaEmbed", "|",
            "undo", "redo"
        ],
        "language": "vi",
        "fontColor": {
            "colors": [
                {"color": "#000000", "label": "Black"},
                {"color": "#FF0000", "label": "Red"},
                {"color": "#0000FF", "label": "Blue"}
            ],
            "columns": 3
        },
        "fontFamily": {
            "options": [
                "default",
                "Arial, sans-serif",
                "Times New Roman, serif",
                "Courier New, monospace"
            ],
            "supportAllValues": True
        },
        "editorPlaceholder": "Nhập nội dung tại đây...",
        "htmlSupport": {
            "allow": [
                {"name": "span", "attributes": ["style"]}
            ]
        },
        "defaultStyle": {  
            "color": "#000000"  # Đặt màu chữ mặc định là đen
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'recruitment_project',
        'USER': 'root',
        'PASSWORD': '123123',
        'HOST': 'localhost',  # Hoặc địa chỉ IP của máy chủ MySQL
        'PORT': '3306',       # Cổng mặc định của MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "home/static",
    BASE_DIR / "job/static",

]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
