# Generated by Django 5.1.2 on 2025-03-10 10:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/', verbose_name='Hình ảnh')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Giới thiệu công ty',
                'verbose_name_plural': 'Giới thiệu công ty',
            },
        ),
    ]
