# Generated by Django 5.1.2 on 2025-03-13 11:30

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên của ứng viên')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('status', models.CharField(choices=[('Độc thân', 'Độc thân'), ('Đã kết hôn', 'Đã kết hôn')], max_length=20, verbose_name='Tình trạng hôn nhân')),
                ('cccd', models.CharField(blank=True, max_length=12, null=True, verbose_name='CCCD/CMND')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí ứng tuyển')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã/Phường')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể')),
                ('education', models.CharField(max_length=255, verbose_name='Trình độ học vấn')),
                ('experience', models.CharField(max_length=255, verbose_name='Kinh nghiệm')),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Website', 'Website'), ('Người quen giới thiệu', 'Người quen giới thiệu'), ('Khác', 'Khác')], max_length=50, verbose_name='Nguồn ứng tuyển')),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/cv/', verbose_name='Hồ sơ ứng viên')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='uploads/portrait/', verbose_name='Ảnh chân dung')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
            ],
            options={
                'verbose_name': 'Ứng viên',
                'verbose_name_plural': 'Danh sách ứng viên',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Xác nhận ứng tuyển: {job_title}', max_length=255, verbose_name='Tiêu đề Email')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(default='Bạn có thể sử dụng các biến sau trong email:<br>- Họ tên: {full_name}<br>- Ngày sinh: {dob}<br>- Số điện thoại: {phone}<br>- Email: {email}<br>- Địa chỉ: {street}, {ward}, {district}, {city}<br>- Học vấn: {education}<br>- Kinh nghiệm: {experience}<br>- Vị trí: {job_title}', verbose_name='Nội dung Email')),
                ('signature_url', models.URLField(blank=True, null=True, verbose_name='URL Chữ ký (Google Drive link)')),
            ],
            options={
                'verbose_name_plural': 'Mẫu Email',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Tên viết tắt')),
                ('title', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('specialty', models.CharField(choices=[('Nhi Khoa 315', 'Nhi Khoa 315'), ('Sản Phụ Khoa 315', 'Sản Phụ Khoa 315'), ('Tim Mạch Tiểu Đường 315', 'Tim Mạch Tiểu Đường 315'), ('Mắt 315', 'Mắt 315'), ('Đa Khoa Quốc Tế IVYHEALTH', 'Đa Khoa Quốc Tế IVYHEALTH'), ('Tiêm Chủng', 'Tiêm Chủng'), ('Văn Phòng', 'Văn Phòng')], max_length=255, verbose_name='Chuyên khoa')),
                ('expertise', models.CharField(choices=[('Kiểm soát nội bộ', 'Kiểm soát nội bộ'), ('Thu mua Dược', 'Thu mua Dược'), ('Thu mua Vật tư - Set up', 'Thu mua Vật tư - Set up'), ('Triển Khai - Hồ sơ', 'Triển Khai - Hồ sơ'), ('Kỹ thuật', 'Kỹ thuật'), ('IT - Phần mềm', 'IT - Phần mềm'), ('Kỹ Thuật viên', 'Kỹ Thuật viên'), ('Kế toán', 'Kế toán'), ('Marketing', 'Marketing'), ('Nhân sự', 'Nhân sự'), ('Quản lý vận hành Lễ Tân', 'Quản lý vận hành Lễ Tân'), ('Quản lý vận hành Dược', 'Quản lý vận hành Dược'), ('Quản lý vận hành Tiêm chủng', 'Quản lý vận hành Tiêm chủng'), ('Kho tổng', 'Kho tổng'), ('Hành chánh', 'Hành chánh'), ('Tài chính', 'Tài chính'), ('Quản lý dự án', 'Quản lý dự án'), ('Trợ lý BGĐ', 'Trợ lý BGĐ'), ('Quản lý chất lượng', 'Quản lý chất lượng'), ('Bác sĩ', 'Bác sĩ'), ('Điều dưỡng', 'Điều dưỡng'), ('Dược sĩ', 'Dược sĩ'), ('Lễ tân', 'Lễ tân'), ('Bảo vệ', 'Bảo vệ')], max_length=255, verbose_name='Chuyên môn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Hình ảnh')),
                ('deadline', models.DateField(verbose_name='Hạn nộp CV')),
                ('location', models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('An Giang', 'An Giang'), ('Bà Rịa - Vũng Tàu', 'Bà Rịa - Vũng Tàu'), ('Bắc Giang', 'Bắc Giang'), ('Bắc Kạn', 'Bắc Kạn'), ('Bạc Liêu', 'Bạc Liêu'), ('Bắc Ninh', 'Bắc Ninh'), ('Bến Tre', 'Bến Tre'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Bình Phước', 'Bình Phước'), ('Bình Thuận', 'Bình Thuận'), ('Cà Mau', 'Cà Mau'), ('Cần Thơ', 'Cần Thơ'), ('Cao Bằng', 'Cao Bằng'), ('Đà Nẵng', 'Đà Nẵng'), ('Đắk Lắk', 'Đắk Lắk'), ('Đắk Nông', 'Đắk Nông'), ('Điện Biên', 'Điện Biên'), ('Đồng Nai', 'Đồng Nai'), ('Đồng Tháp', 'Đồng Tháp'), ('Gia Lai', 'Gia Lai'), ('Hà Giang', 'Hà Giang'), ('Hà Nam', 'Hà Nam'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Hải Dương', 'Hải Dương'), ('Hải Phòng', 'Hải Phòng'), ('Hậu Giang', 'Hậu Giang'), ('Hòa Bình', 'Hòa Bình'), ('Hưng Yên', 'Hưng Yên'), ('Khánh Hòa', 'Khánh Hòa'), ('Kiên Giang', 'Kiên Giang'), ('Kon Tum', 'Kon Tum'), ('Lai Châu', 'Lai Châu'), ('Lâm Đồng', 'Lâm Đồng'), ('Lạng Sơn', 'Lạng Sơn'), ('Lào Cai', 'Lào Cai'), ('Long An', 'Long An'), ('Nam Định', 'Nam Định'), ('Nghệ An', 'Nghệ An'), ('Ninh Bình', 'Ninh Bình'), ('Ninh Thuận', 'Ninh Thuận'), ('Phú Thọ', 'Phú Thọ'), ('Phú Yên', 'Phú Yên'), ('Quảng Bình', 'Quảng Bình'), ('Quảng Nam', 'Quảng Nam'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Ninh', 'Quảng Ninh'), ('Quảng Trị', 'Quảng Trị'), ('Sóc Trăng', 'Sóc Trăng'), ('Sơn La', 'Sơn La'), ('Tây Ninh', 'Tây Ninh'), ('Thái Bình', 'Thái Bình'), ('Thái Nguyên', 'Thái Nguyên'), ('Thanh Hóa', 'Thanh Hóa'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Tiền Giang', 'Tiền Giang'), ('Trà Vinh', 'Trà Vinh'), ('Tuyên Quang', 'Tuyên Quang'), ('Vĩnh Long', 'Vĩnh Long'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Yên Bái', 'Yên Bái')], max_length=255, verbose_name='Vị trí làm việc')),
                ('office', models.CharField(max_length=255, verbose_name='Văn phòng làm việc')),
                ('salary', models.CharField(max_length=255, verbose_name='Thu nhập')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Thực tập', 'Thực tập')], max_length=255, verbose_name='Hình thức làm việc')),
                ('degree', models.CharField(max_length=255, verbose_name='Bằng cấp yêu cầu')),
                ('experience', models.CharField(max_length=255, verbose_name='Kinh nghiệm')),
                ('gender', models.CharField(choices=[('Không yêu cầu', 'Không yêu cầu'), ('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=255, verbose_name='Giới tính yêu cầu')),
                ('level', models.CharField(choices=[('manager', 'Quản Lý'), ('head', 'Trưởng Phòng'), ('assistant', 'Trợ Lý'), ('staff', 'Nhân Viên'), ('intern', 'Công Tác Viên')], max_length=255, verbose_name='Cấp bậc')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng tuyển dụng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('benefits', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Phúc lợi')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Yêu cầu công việc')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mô tả công việc')),
                ('rights', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Quyền lợi')),
            ],
            options={
                'verbose_name_plural': 'Danh sách công việc',
            },
        ),
    ]
