# Generated by Django 5.1.2 on 2025-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
