# Generated by Django 5.1.2 on 2025-03-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Tên viết tắt'),
        ),
    ]
