# Generated by Django 5.1.2 on 2025-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('status', models.CharField(choices=[('Độc thân', 'Độc thân'), ('Đã kết hôn', 'Đã kết hôn')], max_length=20)),
                ('cmnd', models.CharField(blank=True, max_length=12, null=True)),
                ('cccd', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Website', 'Website'), ('Người quen giới thiệu', 'Người quen giới thiệu'), ('Khác', 'Khác')], max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/cv/')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='uploads/portrait/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
