# Generated by Django 5.1.2 on 2025-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expertise',
            field=models.CharField(choices=[('kiemsoat', 'Kiểm soát nội bộ'), ('thuocduoc', 'Thu mua Dược'), ('vatset', 'Thu mua Vật tư - Set up'), ('trienkhai', 'Triển Khai - Hồ sơ'), ('kythuat', 'Kỹ thuật'), ('itphanmem', 'IT - Phần mềm'), ('kythuatvien', 'Kỹ Thuật viên'), ('ketoan', 'Kế toán'), ('marketing', 'Marketing'), ('nhansu', 'Nhân sự'), ('le_tan', 'Quản lý vận hành Lễ Tân'), ('duoc', 'Quản lý vận hành Dược'), ('tiemchung_vh', 'Quản lý vận hành Tiêm chủng'), ('khotong', 'Kho tổng'), ('hanhchanh', 'Hành chánh'), ('taichinh', 'Tài chính'), ('duan', 'Quản lý dự án'), ('troly', 'Trợ lý BGĐ'), ('chatluong', 'Quản lý chất lượng'), ('bacsi', 'Bác sĩ'), ('dieu_duong', 'Điều dưỡng'), ('duocsivien', 'Dược sĩ'), ('le_tan', 'Lễ tân'), ('baove', 'Bảo vệ')], max_length=50, verbose_name='Chuyên môn'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('manager', 'Quản Lý'), ('head', 'Trưởng Phòng'), ('assistant', 'Trợ Lý'), ('staff', 'Nhân Viên'), ('intern', 'Công Tác Viên')], max_length=255, verbose_name='Cấp bậc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('angiang', 'An Giang'), ('bariavungtau', 'Bà Rịa - Vũng Tàu'), ('bacgiang', 'Bắc Giang'), ('backan', 'Bắc Kạn'), ('baclieu', 'Bạc Liêu'), ('bacninh', 'Bắc Ninh'), ('bentre', 'Bến Tre'), ('binhduong', 'Bình Dương'), ('binhdinh', 'Bình Định'), ('binhphuoc', 'Bình Phước'), ('binhthuan', 'Bình Thuận'), ('camau', 'Cà Mau'), ('cantho', 'Cần Thơ'), ('caobang', 'Cao Bằng'), ('danang', 'Đà Nẵng'), ('daklak', 'Đắk Lắk'), ('daknong', 'Đắk Nông'), ('dienbien', 'Điện Biên'), ('dongnai', 'Đồng Nai'), ('dongthap', 'Đồng Tháp'), ('gialai', 'Gia Lai'), ('hagiang', 'Hà Giang'), ('hanam', 'Hà Nam'), ('hatinh', 'Hà Tĩnh'), ('haiduong', 'Hải Dương'), ('haiphong', 'Hải Phòng'), ('haugiang', 'Hậu Giang'), ('hoabinh', 'Hòa Bình'), ('hungyen', 'Hưng Yên'), ('khanhhoa', 'Khánh Hòa'), ('kiengiang', 'Kiên Giang'), ('kontum', 'Kon Tum'), ('laichau', 'Lai Châu'), ('lamdong', 'Lâm Đồng'), ('langson', 'Lạng Sơn'), ('laocai', 'Lào Cai'), ('longan', 'Long An'), ('namdinh', 'Nam Định'), ('nghean', 'Nghệ An'), ('ninhbinh', 'Ninh Bình'), ('ninhthuan', 'Ninh Thuận'), ('phutho', 'Phú Thọ'), ('phuyen', 'Phú Yên'), ('quangbinh', 'Quảng Bình'), ('quangnam', 'Quảng Nam'), ('quangngai', 'Quảng Ngãi'), ('quangninh', 'Quảng Ninh'), ('quangtri', 'Quảng Trị'), ('soctrang', 'Sóc Trăng'), ('sonla', 'Sơn La'), ('tayninh', 'Tây Ninh'), ('thaibinh', 'Thái Bình'), ('thainguyen', 'Thái Nguyên'), ('thanhhoa', 'Thanh Hóa'), ('thuathienhue', 'Thừa Thiên Huế'), ('tiengiang', 'Tiền Giang'), ('travinh', 'Trà Vinh'), ('tuyenquang', 'Tuyên Quang'), ('vinhlong', 'Vĩnh Long'), ('vinhphuc', 'Vĩnh Phúc'), ('yenbai', 'Yên Bái')], max_length=255, verbose_name='Vị trí làm việc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='specialty',
            field=models.CharField(choices=[('nhi', 'Nhi Khoa 315'), ('san', 'Sản Phụ Khoa 315'), ('tim', 'Tim Mạch Tiểu Đường 315'), ('mat', 'Mắt 315'), ('ivhealth', 'Phòng Khám Đa Khoa Quốc Tế IVYHEALTH'), ('tiemchung', 'Tiêm Chủng'), ('vanphong', 'Văn Phòng')], max_length=50, verbose_name='Chuyên khoa'),
        ),
    ]
