# Generated by Django 5.1.2 on 2025-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_expertise_alter_job_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='cmnd',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
