# Generated by Django 5.1.2 on 2025-03-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_applicant_address_remove_applicant_cmnd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Ứng viên', 'verbose_name_plural': 'Danh sách ứng viên'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CCCD/CMND'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cv/', verbose_name='Hồ sơ đính kèm'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='dob',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(max_length=255, verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Kinh nghiệm'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/portrait/', verbose_name='Ảnh chân dung'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='source',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Website', 'Website'), ('Người quen giới thiệu', 'Người quen giới thiệu'), ('Khác', 'Khác')], max_length=50, verbose_name='Nguồn ứng tuyển'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Độc thân', 'Độc thân'), ('Đã kết hôn', 'Đã kết hôn')], max_length=20, verbose_name='Tình trạng hôn nhân'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã/Phường'),
        ),
    ]
