# Generated by Django 5.1.2 on 2025-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_applicant_options_applicant_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Vị Trí'),
        ),
    ]
