# Generated by Django 5.1.2 on 2025-03-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_applicant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='title',
        ),
    ]
