# Generated by Django 5.1.2 on 2025-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_applicant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí ứng tuyển'),
        ),
    ]
