# Generated by Django 5.1.2 on 2025-03-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applicant_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cv/', verbose_name='Hồ sơ ứng viên'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expertise',
            field=models.CharField(choices=[('Kiểm soát nội bộ', 'Kiểm soát nội bộ'), ('Thu mua Dược', 'Thu mua Dược'), ('Thu mua Vật tư - Set up', 'Thu mua Vật tư - Set up'), ('Triển Khai - Hồ sơ', 'Triển Khai - Hồ sơ'), ('Kỹ thuật', 'Kỹ thuật'), ('IT - Phần mềm', 'IT - Phần mềm'), ('Kỹ Thuật viên', 'Kỹ Thuật viên'), ('Kế toán', 'Kế toán'), ('Marketing', 'Marketing'), ('Nhân sự', 'Nhân sự'), ('Quản lý vận hành Lễ Tân', 'Quản lý vận hành Lễ Tân'), ('Quản lý vận hành Dược', 'Quản lý vận hành Dược'), ('Quản lý vận hành Tiêm chủng', 'Quản lý vận hành Tiêm chủng'), ('Kho tổng', 'Kho tổng'), ('Hành chánh', 'Hành chánh'), ('Tài chính', 'Tài chính'), ('Quản lý dự án', 'Quản lý dự án'), ('Trợ lý BGĐ', 'Trợ lý BGĐ'), ('Quản lý chất lượng', 'Quản lý chất lượng'), ('Bác sĩ', 'Bác sĩ'), ('Điều dưỡng', 'Điều dưỡng'), ('Dược sĩ', 'Dược sĩ'), ('Lễ tân', 'Lễ tân'), ('Bảo vệ', 'Bảo vệ')], max_length=255, verbose_name='Chuyên môn'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('Không yêu cầu', 'Không yêu cầu'), ('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=255, verbose_name='Giới tính yêu cầu'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Thực tập', 'Thực tập')], max_length=255, verbose_name='Hình thức làm việc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('An Giang', 'An Giang'), ('Bà Rịa - Vũng Tàu', 'Bà Rịa - Vũng Tàu'), ('Bắc Giang', 'Bắc Giang'), ('Bắc Kạn', 'Bắc Kạn'), ('Bạc Liêu', 'Bạc Liêu'), ('Bắc Ninh', 'Bắc Ninh'), ('Bến Tre', 'Bến Tre'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Bình Phước', 'Bình Phước'), ('Bình Thuận', 'Bình Thuận'), ('Cà Mau', 'Cà Mau'), ('Cần Thơ', 'Cần Thơ'), ('Cao Bằng', 'Cao Bằng'), ('Đà Nẵng', 'Đà Nẵng'), ('Đắk Lắk', 'Đắk Lắk'), ('Đắk Nông', 'Đắk Nông'), ('Điện Biên', 'Điện Biên'), ('Đồng Nai', 'Đồng Nai'), ('Đồng Tháp', 'Đồng Tháp'), ('Gia Lai', 'Gia Lai'), ('Hà Giang', 'Hà Giang'), ('Hà Nam', 'Hà Nam'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Hải Dương', 'Hải Dương'), ('Hải Phòng', 'Hải Phòng'), ('Hậu Giang', 'Hậu Giang'), ('Hòa Bình', 'Hòa Bình'), ('Hưng Yên', 'Hưng Yên'), ('Khánh Hòa', 'Khánh Hòa'), ('Kiên Giang', 'Kiên Giang'), ('Kon Tum', 'Kon Tum'), ('Lai Châu', 'Lai Châu'), ('Lâm Đồng', 'Lâm Đồng'), ('Lạng Sơn', 'Lạng Sơn'), ('Lào Cai', 'Lào Cai'), ('Long An', 'Long An'), ('Nam Định', 'Nam Định'), ('Nghệ An', 'Nghệ An'), ('Ninh Bình', 'Ninh Bình'), ('Ninh Thuận', 'Ninh Thuận'), ('Phú Thọ', 'Phú Thọ'), ('Phú Yên', 'Phú Yên'), ('Quảng Bình', 'Quảng Bình'), ('Quảng Nam', 'Quảng Nam'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Ninh', 'Quảng Ninh'), ('Quảng Trị', 'Quảng Trị'), ('Sóc Trăng', 'Sóc Trăng'), ('Sơn La', 'Sơn La'), ('Tây Ninh', 'Tây Ninh'), ('Thái Bình', 'Thái Bình'), ('Thái Nguyên', 'Thái Nguyên'), ('Thanh Hóa', 'Thanh Hóa'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Tiền Giang', 'Tiền Giang'), ('Trà Vinh', 'Trà Vinh'), ('Tuyên Quang', 'Tuyên Quang'), ('Vĩnh Long', 'Vĩnh Long'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Yên Bái', 'Yên Bái')], max_length=255, verbose_name='Vị trí làm việc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=255, verbose_name='Thu nhập'),
        ),
        migrations.AlterField(
            model_name='job',
            name='specialty',
            field=models.CharField(choices=[('Nhi Khoa 315', 'Nhi Khoa 315'), ('Sản Phụ Khoa 315', 'Sản Phụ Khoa 315'), ('Tim Mạch Tiểu Đường 315', 'Tim Mạch Tiểu Đường 315'), ('Mắt 315', 'Mắt 315'), ('Phòng Khám Đa Khoa Quốc Tế IVYHEALTH', 'Phòng Khám Đa Khoa Quốc Tế IVYHEALTH'), ('Tiêm Chủng', 'Tiêm Chủng'), ('Văn Phòng', 'Văn Phòng')], max_length=255, verbose_name='Chuyên khoa'),
        ),
    ]
