# Generated by Django 5.1.2 on 2025-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='specialty',
            field=models.CharField(choices=[('Nhi Khoa 315', 'Nhi Khoa 315'), ('Sản Phụ Khoa 315', 'Sản Phụ Khoa 315'), ('Tim Mạch Tiểu Đường 315', 'Tim Mạch Tiểu Đường 315'), ('Mắt 315', 'Mắt 315'), ('Đa Khoa Quốc Tế IVYHEALTH', 'Đa Khoa Quốc Tế IVYHEALTH'), ('Tiêm Chủng', 'Tiêm Chủng'), ('Văn Phòng', 'Văn Phòng')], max_length=255, verbose_name='Chuyên khoa'),
        ),
    ]
