# Generated by Django 5.1.2 on 2025-03-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_received', 'Thư cảm ơn sau khi ứng tuyển'), ('interview_invite', 'Thư mời phỏng vấn')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Dùng @name, @position, @specialty để thay thế dữ liệu ứng viên.')),
            ],
        ),
    ]
