# Generated by Django 5.1.2 on 2025-03-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_emailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
