# Generated by Django 5.1.2 on 2025-03-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_emailtemplate_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='Nội dung email mặc định', verbose_name='Nội dung Email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Nội dung email mặc định', max_length=255, verbose_name='Tiêu đề Email'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
