# Generated by Django 5.1.2 on 2025-03-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_emailtemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name_plural': 'Mẫu Email'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='Nội dung email mặc định', help_text='Bạn có thể sử dụng các biến sau trong email:<br>- Họ tên: {full_name}<br>- Ngày sinh: {dob}<br>- Số điện thoại: {phone}<br>- Email: {email}<br>- Địa chỉ: {street}, {ward}, {district}, {city}<br>- Học vấn: {education}<br>- Kinh nghiệm: {experience}<br>- Vị trí: {job_title}', verbose_name='Nội dung Email'),
        ),
    ]
