# Generated by Django 5.1.2 on 2025-03-13 03:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_emailtemplate_options_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Bạn có thể sử dụng các biến sau trong email:<br>- Họ tên: {full_name}<br>- Ngày sinh: {dob}<br>- Số điện thoại: {phone}<br>- Email: {email}<br>- Địa chỉ: {street}, {ward}, {district}, {city}<br>- Học vấn: {education}<br>- Kinh nghiệm: {experience}<br>- Vị trí: {job_title}', verbose_name='Nội dung Email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Xác nhận ứng tuyển: {job_title}', max_length=255, verbose_name='Tiêu đề Email'),
        ),
    ]
