# Generated by Django 5.1.2 on 2025-03-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_emailtemplate_body_alter_emailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='email_signatures/', verbose_name='Chữ ký (hình ảnh)'),
        ),
    ]
