# Generated by Django 5.1.2 on 2025-03-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_emailtemplate_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='signature',
        ),
    ]
