# Generated by Django 5.1.2 on 2025-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_remove_emailtemplate_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='signature_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Chữ ký (Google Drive Direct Link)'),
        ),
    ]
