# Generated by Django 5.1.2 on 2025-03-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='signature_url',
            field=models.URLField(blank=True, default='Link có dạng https://drive.google.com/uc?export=view&id=1A2B3C4D5E6F7G8H9I', null=True, verbose_name='URL Chữ ký (Google Drive Direct Link)'),
        ),
    ]
