# Generated by Django 5.1.2 on 2025-03-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_emailtemplate_signature_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name_plural': 'Mẫu Email'},
        ),
    ]
