# Generated by Django 5.1.2 on 2025-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_alter_emailtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='signature_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Chữ ký (Link có dạng https://drive.google.com/uc?export=view&id=1A2B3C4D5E6F7G8H9I)'),
        ),
    ]
