# Generated by Django 5.1.2 on 2025-03-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_alter_emailtemplate_signature_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='signature_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Chữ ký (Google Drive link)'),
        ),
    ]
