# Generated by Django 5.1.2 on 2025-03-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_emailtemplate_signature_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Danh sách công việc'},
        ),
    ]
