# Generated by Django 5.1.2 on 2024-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
